// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/about.tsx";
import * as $5 from "./routes/credits.tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/MenuLink.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/about.tsx": $4,
    "./routes/credits.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/MenuLink.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
